services:
  - type: web
    name: tutorbay-ae
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start -- -p $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
